In [285]:
import requests
from pathlib import Path
import pandas as pd

In [286]:
server = "https://opendata.aemet.es/opendata"
headers = {
    "api_key" : "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW50aWFnb2xpbGxvbWFjaWFzQGdtYWlsLmNvbSIsImp0aSI6ImJmNjZkMDVmLWY5ODgtNDA2Zi04NjBlLTk5YjJmYjUwYTg1NSIsImV4cCI6MTgwMTI0ODg2NywiaXNzIjoiQUVNRVQiLCJpYXQiOjE3OTI2MDg4NjcsInVzZXJJZCI6ImJmNjZkMDVmLWY5ODgtNDA2Zi04NjBlLTk5YjJmYjUwYTg1NSIsInJvbGUiOiIifQ.sq4eDbdZtCob9SUqoYj9DSxvSpAD2X7t7wAAo3YAhok"
}

In [287]:
requests.get(server, headers=headers)
print("Succesful!")

Succesful!

### Climatología diaria durante el mes de octubre de 2019 en la Ciudad Universitaria de Madrid

#### Obtenemos el idema

In [288]:
requests.get(
    "https://opendata.aemet.es/opendata/api/valores/climatologicos/inventarioestaciones/todasestaciones",
    headers=headers
).json()

{'descripcion': 'exito',
 'estado': 200,
 'datos': 'https://opendata.aemet.es/opendata/sh/23312edc',
 'metadatos': 'https://opendata.aemet.es/opendata/sh/0556af7a'}

In [289]:
request_estaciones = requests.get(
    "https://opendata.aemet.es/opendata/api/valores/climatologicos/inventarioestaciones/todasestaciones",
    headers=headers
).json().get("datos")

#requests.get("https://opendata.aemet.es/opendata/api/valores/climatologicos/inventarioestaciones/todasestaciones",headers=headers).json().get("datos")

In [290]:
# Es una lista, cada elemento es un diccionario
lista_estaciones = requests.get(
    url=request_estaciones,
    headers=headers
    ).json()

#requests.get(url=request_estaciones,headers=headers).json()

In [291]:
df_estaciones = pd.DataFrame(lista_estaciones)
df_estaciones.head()

,latitud,provincia,altitud,indicativo,nombre,indsinop,longitud
0,394924N,ILLES BALEARS,490,B013X,"ESCORCA, LLUC",08304,025309E
1,394744N,BALEARES,5,B051A,"SÓLLER, PUERTO",08316,024129E
2,394121N,BALEARES,60,B087X,BANYALBUFAR,,023046E
3,393446N,BALEARES,52,B103B,ANDRATX - SANT ELM,,022208E
4,393305N,BALEARES,50,B158X,"CALVIÀ, ES CAPDELLÀ",,022759E

In [292]:
df_estaciones.loc[df_estaciones["provincia"] == "MADRID"]

,latitud,provincia,altitud,indicativo,nombre,indsinop,longitud
354,404736N,MADRID,1892,2462,PUERTO DE NAVACERRADA,08215,040039W
418,400402N,MADRID,540,3100B,ARANJUEZ,08229,033246W
420,405323N,MADRID,1159,3104Y,RASCAFRÍA,,035318W
421,410025N,MADRID,1030,3110C,BUITRAGO DEL LOZOYA,08146,033650W
422,410809N,MADRID,1454,3111D,SOMOSIERRA,08145,033449W
423,403300N,MADRID,672,3125Y,SAN SEBASTIÁN DE LOS REYES,,033700W
424,403341N,MADRID,740,3126Y,"MADRID, EL GOLOSO",,034243W
425,402800N,MADRID,609,3129,MADRID AEROPUERTO,08221,033320W
431,403142N,MADRID,605,3170Y,ALCALA DE HENARES,,031723W
432,402919N,MADRID,607,3175,TORREJÓN DE ARDOZ,08227,032637W
433,401842N,MADRID,533,3182Y,ARGANDA DEL REY,,032952W
434,404146N,MADRID,1004,3191E,COLMENAR VIEJO,08219,034554W
435,402706N,MADRID,664,3194U,"MADRID, CIUDAD UNIVERSITARIA",08220,034327W
436,402654N,MADRID,665,3194Y,POZUELO DE ALARCÓN,,034848W
437,402441N,MADRID,667,3195,"MADRID, RETIRO",08222,034040W
438,402232N,MADRID,690,3196,"MADRID, CUATRO VIENTOS",08223,034710W
439,401758N,MADRID,620,3200,GETAFE,08224,034320W
441,401450N,MADRID,594,3229Y,TIELMES,,031842W
446,404223N,MADRID,1530,3266A,PUERTO ALTO DEL LEÓN,08217,040829W
447,403935N,MADRID,924,3268C,ALPEDRETE,,040103W
451,401847N,MADRID,890,3330Y,ROZAS DE PUERTO REAL,,042914W
453,402543N,MADRID,770,3338,ROBLEDO DE CHAVELA,08212,041455W
454,402948N,MADRID,884,3343Y,VALDEMORILLO,,040340W

In [305]:
fila_ciu = df_estaciones.loc[df_estaciones["nombre"] == "MADRID, CIUDAD UNIVERSITARIA"]
list(fila_ciu["indicativo"])[0]

'3194U'

#### Observamos que existe una estación en Ciudad Universitaria

In [293]:
df_estaciones.iloc[435]

latitud                            402706N
provincia                           MADRID
altitud                                664
indicativo                           3194U
nombre        MADRID, CIUDAD UNIVERSITARIA
indsinop                             08220
longitud                           034327W
Name: 435, dtype: str

`idema` es el `indicativo`

In [294]:
# AEMET espera fechas y estación en la ruta, no como query params (?clave=valor).
path_params = {
    "fechaini": "2019-10-01T00:00:00UTC",
    "fechafin": "2019-11-01T00:00:00UTC",
    "idema": "3194U",
}

endpoint_climatologias_diarias = (
    f"{server}/api/valores/climatologicos/diarios/datos/"
    "fechaini/{fechaini}/fechafin/{fechafin}/estacion/{idema}"
)

url_climatologias_diarias = endpoint_climatologias_diarias.format(**path_params)
requests.get(url_climatologias_diarias, headers=headers).json()

{'descripcion': 'exito',
 'estado': 200,
 'datos': 'https://opendata.aemet.es/opendata/sh/b5b2ca98',
 'metadatos': 'https://opendata.aemet.es/opendata/sh/b3aa9d28'}

In [295]:
url_ciu_diario = requests.get(url_climatologias_diarias, headers=headers).json().get("datos")
url_ciu_diario

'https://opendata.aemet.es/opendata/sh/b5b2ca98'

In [296]:
octubre_ciu = requests.get(url=url_ciu_diario, headers=headers).json()
df_ciu = pd.DataFrame(octubre_ciu)
df_ciu.head()

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,tmax,horatmax,hrMedia,hrMax,horaHrMax,hrMin,horaHrMin,pintMax,horaPIntMax
0,2019-10-01,3194U,"MADRID, CIUDAD UNIVERSITARIA",MADRID,664,"19,0","0,0","10,0",06:00,"28,1",14:20,41,62,Varias,27,14:00,"0,0",NaN
1,2019-10-02,3194U,"MADRID, CIUDAD UNIVERSITARIA",MADRID,664,"18,0","0,0","11,5",06:50,"24,5",14:30,44,67,06:30,30,Varias,"0,0",NaN
2,2019-10-03,3194U,"MADRID, CIUDAD UNIVERSITARIA",MADRID,664,"16,9","0,0","7,9",06:40,"25,9",15:20,45,79,Varias,27,Varias,"0,0",NaN
3,2019-10-04,3194U,"MADRID, CIUDAD UNIVERSITARIA",MADRID,664,"18,8","0,0","8,8",06:00,"28,8",15:40,41,72,06:10,24,16:20,"0,0",NaN
4,2019-10-05,3194U,"MADRID, CIUDAD UNIVERSITARIA",MADRID,664,"18,7","0,0","10,0",06:00,"27,4",16:10,47,78,06:30,29,16:10,"0,0",NaN

#### Explicación `*` y `**`

In [297]:
personas = {
    "chico" : "pepe",
    "chica" : "pepa"
}

print(*personas)

chico chica

```text
print(**personas)
```
falla porque `**personas` internamente devuelve `chico="pepe"`, `chica="pepa"`, y `print()` no sabe qué hacer con las variables `chico` y `chica`. Por eso, `**personas` se pasa como argumento a otra función que sí requiere `chico` y `chica`.

#### Explicación `.format()`

In [298]:
personas = {
    "chico" : "pepe",
    "chica" : "pepa"
}

string = "Bienvenido, {chico}; bienvenida, {chica}"
string.format(**personas)

'Bienvenido, pepe; bienvenida, pepa'